### PR TITLE
Add documentation link to top of page

### PR DESCRIPTION
**Pull request by bfirsh**
I can never find the link buried in the middle of the page.

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 👼
/cc @emilevauge

**Comment by emilevauge** [comment]
Thanks @bfirsh :)
Will make a button instead of simple text in another PR.
LGTM

**Comment by vdemeester** [comment]
:tada:

**Comment by emilevauge** [comment]
It's live: https://traefik.io ;)

**Comment by bfirsh** [comment]
Nice. Thanks. :D

**Pull request merged**
